project:
  type: website
  output-dir: docs

website:
  title: "SONA_NLP_Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Bibliography.qmd
      - Appendix.qmd
      - Plagarism-Declaration.qmd



format:
  html:
    embed-resources: true
    theme: cosmo
    css: styles.css
    toc: true



